/**
 * Simulated vendor database — represents public information gathered
 * from Yelp, Google, BBB, and licensed contractor directories.
 * In production this would be a real web-scraping + API integration.
 *
 * Extended with categories, services, and serviceArea fields for
 * richer matching via ServiceProfile-based vendor discovery.
 */

import type { Vendor } from '@/types';

export const VENDOR_DATABASE: Vendor[] = [
  // HVAC
  {
    id: 'v-hvac-1',
    name: 'AirPro Comfort Solutions',
    specialty: ['hvac', 'heating', 'cooling', 'air_quality'],
    categories: ['hvac'],
    services: ['HVAC tune-up', 'AC repair', 'furnace inspection', 'air quality testing', 'seasonal maintenance'],
    rating: 4.8,
    reviewCount: 312,
    priceRange: 'medium',
    reliabilityScore: 92,
    sources: ['Yelp', 'Google Maps', 'BBB Accredited'],
    bbbStatus: 'ok',
    estimatedPrice: 285,
    availability: '3-5 business days',
    availabilityScore: 0.65,
    location: 'Austin, TX',
    serviceArea: { city: 'Austin', state: 'TX', radiusMiles: 25 },
    yearsInBusiness: 14,
    licensed: true,
    insured: true,
  },
  {
    id: 'v-hvac-2',
    name: 'TempRight Systems',
    specialty: ['hvac', 'heating', 'cooling'],
    categories: ['hvac'],
    services: ['HVAC tune-up', 'AC service', 'heating repair'],
    rating: 4.5,
    reviewCount: 189,
    priceRange: 'low',
    reliabilityScore: 83,
    sources: ['Google Maps', 'HomeAdvisor'],
    estimatedPrice: 210,
    availability: '1-2 business days',
    availabilityScore: 0.85,
    location: 'Austin, TX',
    serviceArea: { city: 'Austin', state: 'TX', radiusMiles: 20 },
    yearsInBusiness: 6,
    licensed: true,
    insured: true,
  },
  {
    id: 'v-hvac-3',
    name: 'Elite Climate Control',
    specialty: ['hvac', 'commercial', 'residential'],
    categories: ['hvac'],
    services: ['HVAC tune-up', 'commercial HVAC', 'furnace inspection', 'duct cleaning', 'refrigerant check'],
    rating: 4.9,
    reviewCount: 540,
    priceRange: 'high',
    reliabilityScore: 97,
    sources: ['Yelp', 'Google Maps', 'Angi', 'BBB Accredited'],
    bbbStatus: 'ok',
    estimatedPrice: 420,
    availability: '7-10 business days',
    availabilityScore: 0.35,
    location: 'Austin, TX',
    serviceArea: { city: 'Austin', state: 'TX', radiusMiles: 40 },
    yearsInBusiness: 22,
    licensed: true,
    insured: true,
  },

  // Plumbing / Water Heater
  {
    id: 'v-plumb-1',
    name: 'FlowStar Plumbing',
    specialty: ['plumbing', 'water_heater', 'pipes'],
    categories: ['plumbing'],
    services: ['water heater replacement', 'tankless installation', 'pipe repair', 'drain cleaning'],
    rating: 4.7,
    reviewCount: 428,
    priceRange: 'medium',
    reliabilityScore: 90,
    sources: ['Yelp', 'Google Maps', 'BBB Accredited'],
    bbbStatus: 'ok',
    estimatedPrice: 1450,
    availability: '2-4 business days',
    availabilityScore: 0.7,
    location: 'Austin, TX',
    serviceArea: { city: 'Austin', state: 'TX', radiusMiles: 30 },
    yearsInBusiness: 18,
    licensed: true,
    insured: true,
  },
  {
    id: 'v-plumb-2',
    name: 'AquaTech Plumbing',
    specialty: ['plumbing', 'water_heater', 'water_treatment'],
    categories: ['plumbing'],
    services: ['water heater replacement', 'water treatment', 'emergency plumbing'],
    rating: 4.4,
    reviewCount: 203,
    priceRange: 'low',
    reliabilityScore: 80,
    sources: ['Google Maps', 'Thumbtack'],
    estimatedPrice: 1200,
    availability: 'Next day',
    availabilityScore: 0.9,
    location: 'Austin, TX',
    serviceArea: { city: 'Austin', state: 'TX', radiusMiles: 15 },
    yearsInBusiness: 5,
    licensed: true,
    insured: false,
  },

  // Roofing
  {
    id: 'v-roof-1',
    name: 'SteelCap Roofing',
    specialty: ['roofing', 'inspection', 'repair', 'replacement'],
    categories: ['roofing'],
    services: ['roof inspection', 'shingle repair', 'leak detection', 'roof replacement'],
    rating: 4.6,
    reviewCount: 267,
    priceRange: 'medium',
    reliabilityScore: 88,
    sources: ['Yelp', 'Google Maps', 'BBB Accredited'],
    bbbStatus: 'ok',
    estimatedPrice: 350,
    availability: '3-7 business days',
    availabilityScore: 0.55,
    location: 'Austin, TX',
    serviceArea: { city: 'Austin', state: 'TX', radiusMiles: 35 },
    yearsInBusiness: 11,
    licensed: true,
    insured: true,
  },
  {
    id: 'v-roof-2',
    name: 'PinnaclePro Roofing',
    specialty: ['roofing', 'gutters', 'siding'],
    categories: ['roofing'],
    services: ['roof inspection', 'gutter installation', 'siding repair', 'storm damage assessment'],
    rating: 4.8,
    reviewCount: 389,
    priceRange: 'high',
    reliabilityScore: 95,
    sources: ['Yelp', 'Google Maps', 'Angi', 'BBB A+ Rating'],
    bbbStatus: 'ok',
    estimatedPrice: 480,
    availability: '5-10 business days',
    availabilityScore: 0.4,
    location: 'Austin, TX',
    serviceArea: { city: 'Austin', state: 'TX', radiusMiles: 50 },
    yearsInBusiness: 19,
    licensed: true,
    insured: true,
  },

  // Electrical
  {
    id: 'v-elec-1',
    name: 'Volt Masters Electric',
    specialty: ['electrical', 'panel_upgrade', 'wiring', 'inspection'],
    categories: ['electrical'],
    services: ['panel inspection', 'panel upgrade', 'breaker replacement', 'wiring inspection', 'code compliance'],
    rating: 4.7,
    reviewCount: 356,
    priceRange: 'medium',
    reliabilityScore: 91,
    sources: ['Yelp', 'Google Maps', 'BBB Accredited'],
    bbbStatus: 'ok',
    estimatedPrice: 2200,
    availability: '5-7 business days',
    availabilityScore: 0.5,
    location: 'Austin, TX',
    serviceArea: { city: 'Austin', state: 'TX', radiusMiles: 30 },
    yearsInBusiness: 16,
    licensed: true,
    insured: true,
  },

  // Fire Safety
  {
    id: 'v-fire-1',
    name: 'SafeGuard Fire Services',
    specialty: ['fire_inspection', 'smoke_detector', 'fire_extinguisher', 'compliance'],
    categories: ['fire_safety'],
    services: ['fire alarm testing', 'smoke detector installation', 'fire extinguisher inspection', 'fire safety compliance'],
    rating: 4.9,
    reviewCount: 512,
    priceRange: 'low',
    reliabilityScore: 96,
    sources: ['Google Maps', 'BBB Accredited', 'State Fire Marshal Directory'],
    bbbStatus: 'ok',
    estimatedPrice: 175,
    availability: 'Next available',
    availabilityScore: 0.75,
    location: 'Austin, TX',
    serviceArea: { city: 'Austin', state: 'TX', radiusMiles: 40 },
    yearsInBusiness: 24,
    licensed: true,
    insured: true,
  },

  // IT / Digital / SSL
  {
    id: 'v-it-1',
    name: 'ClearPath IT Solutions',
    specialty: ['ssl', 'web_security', 'domain', 'backup', 'digital_compliance'],
    categories: ['it_security', 'it_ops'],
    services: ['SSL renewal', 'TLS certificate', 'backup verification', 'AWS S3 restore test', 'disaster recovery', 'domain management'],
    rating: 4.6,
    reviewCount: 144,
    priceRange: 'low',
    reliabilityScore: 89,
    sources: ['Clutch', 'Google Maps', 'Upwork Profile'],
    estimatedPrice: 120,
    availability: 'Same day',
    availabilityScore: 0.9,
    location: 'Remote / Austin, TX',
    serviceArea: { state: 'TX', radiusMiles: 0 },
    yearsInBusiness: 8,
    licensed: true,
    insured: true,
  },

  // License / Legal / Compliance
  {
    id: 'v-legal-1',
    name: 'CompliancePro Advisors',
    specialty: ['business_license', 'gdpr', 'regulatory_compliance', 'documentation'],
    categories: ['compliance'],
    services: ['business license renewal', 'GDPR audit', 'regulatory compliance', 'data retention policy'],
    rating: 4.7,
    reviewCount: 98,
    priceRange: 'medium',
    reliabilityScore: 93,
    sources: ['LinkedIn', 'Google Maps', 'Bar Association'],
    bbbStatus: 'ok',
    estimatedPrice: 350,
    availability: '2-3 business days',
    availabilityScore: 0.65,
    location: 'Austin, TX',
    serviceArea: { city: 'Austin', state: 'TX', radiusMiles: 50 },
    yearsInBusiness: 12,
    licensed: true,
    insured: true,
  },
];
